version: "3.9"

services:
    express-app:
        build: .
        container_name: ollama_backend
        ports:
            - "${PORT:-3001}:3001"
        environment:
            - NODE_ENV=development
            - PORT=${PORT}
            - OLLAMA_URL=${OLLAMA_URL}
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev
