version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8080:8080'
    networks:
      docker-dashboard-net:

networks:
  docker-dashboard-net:
